refactor: allow no I and jsx lambdas
dcos-labs/tslint-config pull request #7
Opened 2018-06-11 21:58 UTC by weblancaster

2018-06-11 21:58 UTC, weblancaster commented on index.js
> +    "interface-name": [
we have only two options `always allow` or `never allow`

2018-06-11 21:59 UTC, weblancaster commented on index.js
> +    "jsx-no-lambda": true
the advantages of not using lambdas in jsx are too small at the moment for.

2018-06-12 06:16 UTC, juliangieseke approved these changes

2018-06-12 07:32 UTC, Poltergeist approved these changes

2018-06-12 08:16 UTC, DanielMSchmidt requested changes
Could you please pull the JIRA for this into the sprint and link it here?

2018-06-12 23:17 UTC, weblancaster commented
@DanielMSchmidt I did not find any Jira, is there one? if not let me know so I can create. Thank you.

2018-06-15 00:58 UTC, weblancaster commented
@DanielMSchmidt can we dismiss your request changes? or if you know there is a Jira please send to me so I can update the PR

2018-06-15 05:42 UTC, DanielMSchmidt approved these changes

2018-06-15 05:43 UTC, DanielMSchmidt commented
@weblancaster Thank you for giving me a reminder, totally forgot that I wanted to unblock this 🙈

2018-06-15 05:43 UTC, merged